BookStore.UI/Controllers/CartController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using BookStore.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.UI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repo;
        private IOrderProcessor orderProcessor;
        public CartController(IBookRepository _repo, IOrderProcessor _orderProcessor)
        {
            repo = _repo;
            orderProcessor = _orderProcessor;
        }
        public RedirectToRouteResult AddToCart(Cart cart, int BookId, string returnUrl)
        {
            Book book = repo.Books.Where(b => b.BookId == BookId).FirstOrDefault();
            if(book != null)
            {
                cart.AddItem(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart, int bookId, string returnUrl)
        {
            Book book = repo.Books.Where(b => b.BookId == bookId).FirstOrDefault();
            if (book != null)
            {
                cart.RemoveItem(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        //private Cart GetCart()
        //{
        //    Cart cart = Session["Cart"] as Cart;
        //    if(cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}

        public ActionResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                cart = cart,
                returnUrl = returnUrl
            });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost ]
        public ViewResult Checkout(Cart cart, ShippingDetails shipDetails)
        {
            if(cart.CartLines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your cart is empty");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shipDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shipDetails);
            }
            
        }
    }
}

BookStore.UI/Controllers/NavController.cs
using BookStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.UI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repo;
        public NavController(IBookRepository _repo)
        {
            repo = _repo;
        }
        // GET: Nav
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.category = category;
            IEnumerable<string> categories = repo.Books
                                            .Select(b => b.Category)
                                            .Distinct();
            //string viewName = mobileLayout ? "MenuHorizontal" : "Menu";
            return PartialView("MenuFlex", categories);
        }

    }
}

BookStore.UI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/ErrorStyle.css" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <div>
        @if(TempData["message"] != null)
        {
            <div class="alert alert-info">
                @TempData["message"]
            </div>
        }
        @RenderBody()
    </div>
</body>
</html>

BookStore.UI/Views/Shared/_BookSummary.cshtml
@model BookStore.Domain.Entities.Book

<div class="">
    <h3><strong>@Model.Title</strong></h3>
    <span class="pull-right label label-primary">
        @Model.Price.ToString("c")
    </span>
    <span class="lead">
        @Model.Description
    </span>
</div>

@using (Html.BeginForm("AddToCart", "Cart"))
{
    <div class="pull-right">
        @Html.HiddenFor(c => c.BookId)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

        <input type="submit" class="btn btn-success" value="Add to cart" />
    </div>
}

BookStore.UI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width; initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    @*<link rel="stylesheet" href="~/Scripts/jquery-1.10.2.min.js"/>*@
    @*<link rel="stylesheet" href="~/Content/"/>*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
</head>
<body>
    <div>
        <div data-role="page" id="page1">
            <div data-theme="true" data-role="header" data-position="fixed">
                <h3>Bookstore</h3>
                @Html.Action("Menu", "Nav")
            </div>
            <div data-role="content">
                <ul data-role="listview" data-dividertheme="b" data-inset="false">
                     @RenderBody()
                </ul>
            </div>       
        </div>      
    </div>
</body>
</html>

BookStore.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/ErrorStyle.css" rel="stylesheet"/>
    <style>
        .navbar-right {
            float:right !important;
            margin-right: 20px;
            margin-left: 20px;

        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">Book store</span>
            <div class="visible-xs">Book</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { mobileLayout = true})
    </div>
    <div class="row panel">
        <div id="spec" class="col-xs-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>